#!/usr/bin/env php
<?php 

// http://www.cafeoto.co.uk/programme.shtm
// http://www.timeout.com/london/venue/14759/cafe_oto.html
// http://www.remotegoat.co.uk/venue_view.php?uid=25219

require dirname(__FILE__) . '/../includes/main.inc.php';

$xml = url_html_xml('http://www.southbankcentre.co.uk/all-events?action=calendar&calendar_selected=2009-01-13');
//$xml = url_html_xml('../files/test.html');

$rows = $xml->xpath('//div[@id="col1"]/div[@class="list"]');

$events = array();

ical_start('Southbank Centre');

foreach ($rows as $row){  
  $datetime = (string) first($row->xpath('div/p[@class="datetime"]'));
  list($start, $end) = explode(' - ', $datetime);
    
  $thumbnail = first($row->xpath('a[@class="noA"]'));
  
  $venue = first($row->xpath('*[@class="venue"]'));
  $price = first($row->xpath('*[@class="price"]'));
  
  $summary = (string) $row->div->h4;
  //printf("\n===\n%s\n===\n", $summary);
  
  $description = first($row->xpath('div/*[@class="info2"]'));
  
  $event = array(
    'start' => strtotime($start),
    'end' => strtotime($end),
    'uri' => make_link($thumbnail['href']),
    'image' => make_link($thumbnail->img['src']),
    'summary' => strip_tags($summary),
    'description' => strip_tags($description->asXML()),
    );
    
  ical_event($event);
  store_event($event);
}

ical_end();

